# Generated by Django 4.1.4 on 2022-12-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskModel",
            new_name="Task",
        ),
    ]
